### ISSUE TITLE
Fix cmake install

### ISSUE THREAD

**Issue by leofang** [conda-forge/thrust-feedstock#14] opened 2022-04-04 03:31 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For context see https://github.com/conda-forge/cub-feedstock/issues/16 and https://github.com/conda-forge/cub-feedstock/issues/17.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by kkraus14** [comment] 2022-04-04 15:30
Duplicate of #12

**Closed as completed by kkraus14** 2022-04-04 15:30 UTC
Labels: bug
